### ISSUE TITLE
City neighborhoods

### ISSUE THREAD

**Issue by sylae** [sylae/devilfish-map#13]
Note: this is not like ashton's shitshow where half the city is miles of abandoned warehouses. no.

but that being said, the city should have some distinct neighborhoods, obviously not as black-and-white as Ashton's were, but something to give them personality. This project will probably be working closely with the street names peeps (#1, #12).

keep in mind the scale of the city

**Comment by Nashoid** [comment]
After some preliminary research, I've determined a city of roughly 115,000 should have roughly 40-45 neighborhoods/districts, This was determined by comparing the number of neighborhoods/districts of cities with similar population.

These might be helpful when designing the map, to ensure we don't have another Ashton with only 10 neighborhoods/districts in total, despite being a fuckoff massive city

**Wealthy Neighborhoods:**

- Canary Hills (Gated Community)
- Greenfield 
- Ridgemont Village
- Point Breeze
- Brighton Heights

**Buisness Parks:**

- Downtown
- Downtown East
- Garden Court 
- Brewery Town (Heavily gentrified)
- Devilfish Financial District (Has some Highrises)
- Park Avenue Historic District (somewhat older well-preserved buildings)
- Jefferson Avenue
- Tower Grove East
- Tower Grove South

**Middle-class Suburbs:**

- Benton Park
- Benton Park West
- Clifton Heights
- College Hills
- West End
- Poplar Springs
- Cloverleaf Acres
- Russel Manor
- Saint Jospeh (Catholic neighborhood)


**Low-income neighborhoods:**

- Piper Glen
- Carmel Village
- Historic South End
- Cherry
- Wesley Heights
- Pine Bluff Hills
- Belmont
- Hickory Ridge

**Industrial Parks:**

- Stonehaven
- Midtown
- Ravenwood
- Mint Hill
- Camp Clifton
- Deer Park
- Wilmore Historical District 
- Reid Park
