### ISSUE TITLE
Devilfish Points of Interest

### ISSUE THREAD

**Issue by Nashoid** [sylae/devilfish-map#16]
This is where we can list some preliminary points of Interest that a city of this size would have
along the lines of Malls, Clinics, Banks, city utilities, etc

**Comment by Nashoid** [comment]
Here are some Preliminary points of interest

**City Services:**
Town Hall
Courthouse
Police Stations
Fire Stations
Waste Management
Sewage Treatment
DMV
Animal Shelter
Landfill
Salvage Yard

**Transportation:**
Bus Depot
Taxi Depot
Train Station
Airport
Trolley system (Historic Districts)
Boat Harbor/Marina

**Education:**
University
Trade School
Highschool
Elementary

**Buisness:**
Banks
Churches
Hospitals
Urgent Care Clinics
Nursing Homes
Vet Hospital
Farmers Market
Brewery (Gentrified Districts)
Indoor Mall

**Entertainment:**
Historic Theater
New Theater
Museum
Zoo
Roller Rink
Bowling Alley
Arcade
Skatepark

**Comment by Nashoid** [comment]
**Fast-food Restaurants that are popular in Minnesota: (Because I was bored, but unable to focus on anything important atm)**

White Castle
Chipotle Mexican Grill
Subway Sandwich Shop
Chick-fil-a
Arbys
Panda Express
Wendys
Sonic Drive-in
McDonalds
Taco Bell
Raising Cane’s Chicken Fingers
Five Guys
KFC
Dairy Queen
Burger King
Quiznos
Long John Silvers
Starbucks
Pizzahut
Dominos 
Wafflehouse
IHOP
Dennys

**Comment by sylae** [comment]
thank you for the help! :) ive added some of these to the map
